version: '3.2'
services:
  schema-vc:
    build:
      context: .
      dockerfile: Dockerfile

  ui:
    image: node:carbon
    volumes:
      - ./ui:/ui    
      - ./server/public:/ui/build
    working_dir: /ui

  nginx:
    image: nginx
    volumes:
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./server/public:/ui
      - ./server/logs:/logs
    links:
      - schema-vc 
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host

